# Aggregate results monthly

In [1]:
# --------------------------------------------------------
# import necessary packages
# --------------------------------------------------------
from matplotlib import pyplot as plt
import pandas as pd
from py_eddy_tracker import data
from py_eddy_tracker.dataset.grid import RegularGridDataset
import xarray as xr
from datetime import datetime
import numpy as np
from netCDF4 import Dataset
import warnings
warnings.filterwarnings('ignore')

In [2]:
# These need to be specified
domain='whole'
Lcutoff=500
sshmin=0.06

In [3]:
Years = np.arange(2003,2022,1)
Months= np.arange(4,10,1)
#
Acounts=np.zeros((np.size(Months),np.size(Years)))
Aanom=np.zeros((np.size(Months),5))
#
for m,MON in enumerate(Months):
    anom=np.array([])
    for n,YYYY in enumerate(Years):
        DAY=15    
        date = datetime(YYYY, MON, DAY)
        fn = date.strftime(f"NPP_Anticyc_{domain}_{Lcutoff}_{sshmin}_%Y%m%d.npy")
        #print(fn)
        tmp=np.load(fn)
        anom = np.concatenate((anom,tmp),axis=0)
        #print(np.mean(tmp))
        Acounts[m,n]=np.size(tmp)
    #
    Aanom[m,0]=MON
    Aanom[m,1]=np.nanmean(anom)
    Aanom[m,2]=np.nanstd(anom)
    Aanom[m,3]=np.size(anom)
    Aanom[m,4]=np.nanstd(anom)/np.sqrt(Aanom[m,2]-1)
    #print(Counts[m])

In [4]:
df_A=pd.DataFrame(Aanom,columns=['Month','mean NPP','stdev','Count','SE'])
df_A.to_csv(f'Anticyc_{domain}_{Lcutoff}_{sshmin}_stats.csv')
df_A

   Month   mean NPP       stdev  Count         SE
0    4.0 -18.997090  167.800669   48.0  12.992562
1    5.0 -26.749123  151.248609   47.0  12.339176
2    6.0  80.741662  160.965875   43.0  12.726827
3    7.0  96.125798  205.748020   33.0  14.378905
4    8.0 -18.341057  148.659847   39.0  12.233831
5    9.0  -4.871874  135.357416   32.0  11.677536

In [5]:
Ccounts=np.zeros((np.size(Months),np.size(Years)))
Canom=np.zeros((np.size(Months),5))
#
for m,MON in enumerate(Months):
    anom=np.array([])
    for n,YYYY in enumerate(Years):
        DAY=15    
        date = datetime(YYYY, MON, DAY)
        fn = date.strftime("NPP_Cyclonic_%Y%m%d.npy")
        #print(fn)
        tmp=np.load(fn)
        anom = np.concatenate((anom,tmp),axis=0)
        #print(np.mean(tmp))
        Ccounts[m,n]=np.size(tmp)
    #
    Canom[m,0]=MON
    Canom[m,1]=np.nanmean(anom)
    Canom[m,2]=np.nanstd(anom)
    Canom[m,3]=np.size(anom)
    Canom[m,4]=np.nanstd(anom)/np.sqrt(Canom[m,2]-1)
    #print(Counts[m])

In [6]:
df_C=pd.DataFrame(Canom,columns=['Month','mean NPP','stdev','Count','SE'])
df_C.to_csv(f'Cyc_{domain}_{Lcutoff}_{sshmin}_stats.csv')
df_C

   Month    mean NPP       stdev  Count         SE
0    4.0    9.283676    0.000000    1.0        NaN
1    5.0  -25.324419  190.144025    3.0  13.825676
2    6.0         NaN         NaN    0.0        NaN
3    7.0   11.362606    0.000000    1.0        NaN
4    8.0  168.438985    0.000000    1.0        NaN
5    9.0   83.110134  201.918744    2.0  14.245130